spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: 'jdbc:h2:file:C:\Users\putri\database'
    driverClassName: org.h2.Driver
    hikari:
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /db-console
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: UTC
    show-sql: false # Set true for debugging
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)
    open-in-view: false
  sql:
    init:
      platform: h2
      mode: always
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


okta.oauth2.issuer: 'https\://dev-4978011.okta.com/oauth2/default'
okta.oauth2.client-id: '0oa7trrhn4KNtoBcu5d7'
#okta.oauth2.client-secret=${OKTA_CLIENT_SECRET}

spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html

spring.profiles.active: dev,prod
